dist: xenial

branches:
  # We need to whitelist the branches which we want to have "push" automation.
  # Pull request automation is not constrained to this set of branches.
  only:
  - master

matrix:
  fast_finish: true
  include:
    - language: node_js
      node_js: "8"
      env: CXX=g++-4.8 TEST_SUITE=test
      script:
        - npm run $TEST_SUITE

    - language: rust
      install:
        - rustup component add rustfmt
        - rustup target add asmjs-unknown-emscripten
      script:
        # the useful way to run rustfmt
        - cargo fmt --all -- --check
        - cargo build
        - make
