dist: xenial

branches:
  # We need to whitelist the branches which we want to have "push" automation.
  # Pull request automation is not constrained to this set of branches.
  only:
  - master

matrix:
  fast_finish: true
  include:
    - language: node_js
      node_js: "8"
      env: TEST_SUITE=test
      script:
        - npm run $TEST_SUITE

    - language: rust
      install:
        - rustup component add rustfmt
        # install emsdk
        - git clone https://github.com/emscripten-core/emsdk.git
        - ./emsdk/emsdk install sdk-incoming-64bit
        - ./emsdk/emsdk activate sdk-incoming-64bit
        - rustup target add asmjs-unknown-emscripten
      script:
        # the useful way to run rustfmt
        - cargo fmt --all -- --check
        # activate Emscripten
        - source ./emsdk/emsdk_env.sh
        - cargo build
        - make
