dist: xenial

branches:
  # We need to whitelist the branches which we want to have "push" automation.
  # Pull request automation is not constrained to this set of branches.
  only:
  - master

matrix:
  fast_finish: true
  include:
    - language: node_js
      node_js: "8"
      env: TEST_SUITE=test
      script:
        - npm run $TEST_SUITE

    - language: rust
      #rust: "1.27.2"
      #env: EMSDK_VERSION=sdk-1.38.21-64bit
      env: EMSDK_VERSION=latest
      install:
        #- rustup component add rustfmt
        # install emsdk
        - git clone https://github.com/emscripten-core/emsdk.git
        - ./emsdk/emsdk install $EMSDK_VERSION
        - ./emsdk/emsdk activate $EMSDK_VERSION
        - rustup target add asmjs-unknown-emscripten
      script:
        # the useful way to run rustfmt
        - cargo fmt --all -- --check
        # activate Emscripten
        - source ./emsdk/emsdk_env.sh
        # no need to run cargo build anymore
        # https://github.com/ethereumjs/rustbn.js/pull/36/files#r257229082
        #- cargo build
        - make
